### ISSUE TITLE
突然不能使用了

### ISSUE THREAD

**Issue by qihang-dai** [So0ni/cimiss-python#2]
公司内部自己写的可以下载，但是cimiss-python包client.query那里就连接不上

**Comment by So0ni** [comment]
用这个需要转发zeroc的端口  如果不是局端内部使用的话 通常不会做这个端口的转发

**Comment by qihang-dai** [comment]
很奇怪重装zeroc-ice后能用了。不过CIMISS数据量稍微大一点就TIMEOUT了，哎
